export const positions = [
  "Data Scientist",
  "Software Engineer",
  "Product Manager",
  "Designer",
  "DevOps Engineer",
  "QA Engineer",
  "Business Analyst",
  "System Administrator",
  "Database Administrator",
  "Network Engineer",
  "Security Analyst",
  "Technical Support Specialist",
  "Web Developer",
  "Mobile Developer",
  "Cloud Architect",
  "AI/ML Engineer",
  "Full Stack Developer",
  "Front End Developer",
  "Back End Developer",
  "IT Manager",
  "Project Manager",
];
